version: 0.2
phases:
  pre_build:
    commands:
      #- docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - mv docker-compose.prod.yml docker-compose.override.yml
  build:
    commands:
      - docker-compose -f docker-compose.yml -f docker-compose.build.yml build
  post_build:
    commands:
      - docker-compose -f docker-compose.yml -f docker-compose.build.yml push
artifacts:
  files:
    - 'docker-compose.yml'
    - 'docker-compose.override.yml'