version: '3'
services:
  server:
    extends:
      file: docker-compose.services.yml
      service: ${APP_ENV}-server
    build:
      context: .
    container_name: '${APP_NAME}-server'
    restart: 'always'
    ports:
      - "${APP_PORT}:${APP_PORT}"    
    networks:
      - main
    restart: 'always'
    env_file:
      - .env
networks:
  main:
      name: '${APP_NAME}-network'
      driver: bridge 