services:
  dev:
    build:
      target: dev
    volumes:
        - ./app:/usr/src/app
  prod:
    build:
      target: prod
  default:
    networks:
      - main
    restart: 'always'    
    env_file:
      - .env
  

