version: '3.8'
services:
  server:
    container_name: '${APP_NAME}-server' 
    image: ${CONTAINER_REPO}/${APP_NAME}-server:latest
    ports:
      - 443:443
      - 80:80   
    depends_on:
      - app
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
  app:
    image: ${CONTAINER_REPO}/${APP_NAME}-app:latest
    ports:
      - 3000
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
networks:
  default:
    name: '${APP_NAME}-network'
    driver: bridge 