version: '3'
services:
  server:
    extends:
      file: docker-compose.extend.yml
      service: ${APP_ENV}-server
    container_name: '${APP_NAME}-server'
    restart: 'always'
    ports:
      - "3000:3000"    
    networks:
      - main
    restart: 'always'
networks:
  main:
      name: '${APP_NAME}-network'
      driver: bridge 