version: '3.8'
services:
  server:
    extends:
      file: docker-compose.services.yml
      service: ${APP_ENV}-server
    build:
      context: .
      args:
        APP_PORT: ${APP_PORT}
    container_name: '${APP_NAME}-server'
    restart: 'always'
    ports:
      - "${APP_PORT}:${APP_PORT}"    
    networks:
      - main
    restart: 'always'
    environment:
      APP_NAME: ${APP_NAME}
      APP_PORT: ${APP_PORT}
      APP_ENV: ${APP_ENV}
networks:
  main:
      name: '${APP_NAME}-network'
      driver: bridge 