services:
  server:
    container_name: '${APP_NAME}-server' 
    build:
      context: ./nginx
    image: ${CONTAINER_REPO}/${APP_NAME}-server
    ports:
      - 443:443
      - 80:80   
    depends_on:
      - app
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - .env
  app:
    extends:
      file: ./docker-compose.services.yml
      service: ${APP_ENV}-app  
    build:
      context: ./app
    image: ${CONTAINER_REPO}/${APP_NAME}-app
    ports:
      - ${APP_PORT}
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - .env
networks:
  default:
    name: '${APP_NAME}-network'
    driver: bridge 