services:
  dev-app:
    build:
      target: dev
    volumes:
        - ./app:/usr/src/app
  prod-app:
    build:
      target: prod
  general:
    networks:
      - main
    restart: 'always'    
    env_file:
      - .env
  

