services:
  nginx:
    container_name: '${APP_NAME}-server'
    extends:
      file: ./docker-compose.services.yml
      service: default
    build:
       context: ./nginx   
    ports:
      - "${APP_PORT}:${APP_PORT}"   
    depends_on:
      - app1
      - app2
      - app3
  app1:
    container_name: '${APP_NAME}-app1'
    extends:
      file: ./docker-compose.services.yml
      service: default
      service: ${APP_ENV}  
    build:
      context: ./app           
    ports:
      - "3001:3001"       
    environment:
      APP_PORT: 3001
  app2:
    container_name: '${APP_NAME}-app2'
    extends:
      file: ./docker-compose.services.yml
      service: default
      service: ${APP_ENV}  
    build:
      context: ./app           
    ports:
      - "3002:3002"       
    environment:
      APP_PORT: 3002
  app3:
    container_name: '${APP_NAME}-app3'
    extends:
      file: ./docker-compose.services.yml
      service: default
      service: ${APP_ENV}
    build:
      context: ./app             
    ports:
      - "3003:3003"       
    environment:
      APP_PORT: 3003
networks:
  main:
      name: '${APP_NAME}-network'
      driver: bridge 