version: '3.8'
services:
  server:
    build:
      target: dev
      context: ./nginx    
    ports:
      - 443:443
      - 80:80 
    depends_on:
      - app
    restart: on-failure
    env_file:
      - .env
  app:
    build:
      target: dev
      context: ./app
    ports:
      - 3000
    volumes:
      - ./app:/usr/src/app
    deploy:
      mode: replicated
      replicas: ${APP_SCALE}  
    restart: on-failure
    env_file:
      - .env
networks:
  default:
    name: '${APP_NAME}-network'
    driver: bridge 