services:
  server:
    container_name: '${APP_NAME}-server' 
    build:
      context: ./nginx
      args:
        SERVER_HOST: ${SERVER_HOST}
        SSL_TYPE: ${SSL_TYPE}
    volumes:
      - ssl:/etc/letsencrypt
    ports:
      - 443:443
      - 80:80   
    depends_on:
      - app
    restart: 'always' 
    env_file:
      - .env
  app:
    extends:
      file: ./docker-compose.services.yml
      service: ${APP_ENV}-app  
    build:
      context: ./app
    expose:
      - ${APP_PORT}
    restart: 'always'    
    env_file:
      - .env
volumes:
  ssl:
    name: ${APP_NAME}-ssl
networks:
  default:
    name: '${APP_NAME}-network'
    driver: bridge 