version: '3.8'
services:
  server:
    image: ${DOCKER_REPO}/${APP_NAME}-server:latest 
    ports:
      - 80:80 
    depends_on:
      - app
    deploy:
      restart_policy:
        condition: on-failure
  app:
    image: ${DOCKER_REPO}/${APP_NAME}-app:latest
    ports:
      - 3000
    deploy:
      mode: replicated
      replicas: ${APP_SCALE}  
      restart_policy:
        condition: on-failure      
networks:
  default:
    name: '${APP_NAME}-network'
    driver: bridge