version: '3'
services:
  server:
    build: 
      context: ./
    container_name: '${APP_NAME}-server'
    command: /bin/sh -c "npm install && npm run ${APP_ENV}"
    restart: 'always'
    ports:
      - "3000:3000"  
    #working_dir: /usr/src/app    
    networks:
      - main
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules      
    restart: 'always'
networks:
  main:
      name: '${APP_NAME}-network'
      driver: bridge 